version: "3.8"

services:
  db:
    image: "mysql:5.7"
    restart: "always"
    env_file:
      - "config/mysql.env"
    expose:
      - "3306"
    volumes:
      - "db:/var/lib/mysql"

  app:
    build: "project/"
    env_file:
      - "config/mysql.env"
      - "config/django.env"
    expose:
      - "8000"
    volumes:
      - "./project:/usr/src/app"
    depends_on:
      - "db"

  server:
    image: "nginx:1.19-alpine"
    restart: "always"
    ports:
      - "80:80"
    volumes:
      - "./project/static:/srv"
      - "./config/nginx.conf:/etc/nginx/conf.d/default.conf"
    depends_on:
      - "app"

volumes:
  db:
